-- MIGRATION 03 — Références du groupement (extraites des maquettes, statut publié)
-- À exécuter dans Supabase (SQL Editor). Ré-exécutable : ON CONFLICT (slug) ne double pas.
insert into references_projets (slug, titre, categorie, localisation, description, statut) values
  ('construction-de-40-logements-bertincourt', 'Construction de 40 logements', 'Logement', 'Bertincourt', '40 logements intergénérationnels (Tisserin et Maisons de Marianne).', 'publie'),
  ('optimisation-60-logements-bethune', 'Optimisation 60 logements', 'Logement', 'Béthune', 'Optimisation d''un dossier de 60 logements en R+5 pour le compte de Réalités.', 'publie'),
  ('construction-de-50-logements-emmerin', 'Construction de 50 logements', 'Logement', 'Emmerin', '50 logements en deux bâtiments, certifiés RT2012 BEE+.', 'publie'),
  ('chateau-de-la-roseraie-hem', 'Château de la Roseraie', 'Logement', 'Hem', 'Réhabilitation lourde d''un château en 20 logements collectifs.', 'publie'),
  ('agence-marignan-lille', 'Agence Marignan', 'Bureaux et tertiaires', 'Lille', 'Rénovation et agencement de l''agence Marignan Immobilier.', 'publie'),
  ('chateau-blanc-cftl-wasquehal', 'Château Blanc CFTL', 'Autres ouvrages fonctionnels', 'Wasquehal', 'Réhabilitation d''un bâtiment de bureaux en centre de formation (AFTRAL, ISTELI).', 'publie'),
  ('amazon-dnc1', 'Amazon DNC1', 'Industries et logistiques', null, 'Mezzanine de 700m² à usage de bureaux, réhabilitation de 1500m² de bureaux, cuve incendie.', 'publie'),
  ('open-r-mobivia-mouv-factory', 'Open''R Mobivia — Mouv Factory', 'Bureaux et tertiaires', null, 'Construction de 3 bâtiments de 14000m² pour MOBIVIA (utilisateur) et AEW (investisseur).', 'publie'),
  ('centre-de-formation-sncf-lille-tour-ekla', 'Centre de formation SNCF', 'Bureaux et tertiaires', 'Lille — Tour Ekla', 'Agencement de deux plateaux de bureaux en centre de formation (simulateurs, salles de classe).', 'publie'),
  ('construction-de-49-logements-croix', 'Construction de 49 logements', 'Logement', 'Croix', '49 logements pour Marignan Immo, en 3 cages R+2 sur un niveau de sous-sol.', 'publie'),
  ('rehabilitation-credit-du-nord-valenciennes', 'Réhabilitation Crédit du Nord', 'Bureaux et tertiaires', 'Valenciennes', 'Réhabilitation lourde, bâtiment de 1200m² en R+3 (ERT et ERP).', 'publie'),
  ('20-cellules-d-activite-grande-synthe', '20 cellules d''activité', 'Industries et logistiques', 'Grande-Synthe', 'Construction de 20 cellules d''activité en charpente métallique.', 'publie'),
  ('parc-silo-600-places-euradouai', 'Parc Silo 600 places', 'Autres ouvrages fonctionnels', 'Euradouai', 'Parc de stationnement silo de 600 places, 14000m², 25% IRVE et ombrières photovoltaïques.', 'publie'),
  ('residence-81-logements-lievin', 'Résidence 81 logements', 'Logement', 'Liévin', 'Résidence intergénérationnelle de 81 logements en 2 cages R+3.', 'publie'),
  ('hopital-saint-vincent-lille', 'Hôpital Saint Vincent', 'Hospitalier', 'Lille', 'Création d''un nouveau local scanner.', 'publie'),
  ('edgar-suites-appart-hotel-lille-le-shake', 'Edgar Suites — Appart Hôtel', 'Hôtelleries et restaurations', 'Lille — Le Shake', 'Aménagement d''appart-hôtels au Shake à Lille.', 'publie'),
  ('decathlon-entrepot-logistique-evin-malmaison', 'Decathlon — Entrepôt logistique', 'Industries et logistiques', 'Évin-Malmaison', 'Travaux de puissance relatifs à la mécanisation de l''entrepôt.', 'publie'),
  ('edf-centrale-nucleaire-chooz', 'EDF — Centrale nucléaire', 'Industries et logistiques', 'Chooz', 'Réhabilitation du bâtiment SUC Les Chênes au sein du CNPE, en ZPR.', 'publie'),
  ('banque-de-france-rue-royale-lille', 'Banque de France — Rue Royale', 'Bureaux et tertiaires', 'Lille', 'Réhabilitation et rénovation des espaces tertiaires de la succursale.', 'publie'),
  ('exotec-imaginarium-wasquehal', 'Exotec — Imaginarium', 'Bureaux et tertiaires', 'Wasquehal', 'Construction du siège social EXOTEC.', 'publie'),
  ('afeji-centre-vauban-lille', 'AFEJI — Centre Vauban', 'Bureaux et tertiaires', 'Lille', 'Aménagement du siège régional de l''AFEJI.', 'publie'),
  ('sgami-andv-chanzy', 'SGAMI — ANDV', 'Autres ouvrages fonctionnels', 'Chanzy', 'Aménagement des locaux de l''ANDV dans l''ancienne caserne.', 'publie'),
  ('dalkia-lineo-la-madeleine', 'Dalkia — Lineo', 'Industries et logistiques', 'La Madeleine', 'Aménagement de trois cellules d''activité.', 'publie'),
  ('dalkia-rie-saint-andre', 'Dalkia — RIE', 'Hôtelleries et restaurations', 'Saint-André', 'Aménagement du restaurant d''entreprise de Dalkia.', 'publie'),
  ('ehpad-de-ronchin-ronchin', 'EHPAD de Ronchin', 'Hospitalier', 'Ronchin', 'Mise en œuvre d''un système de rafraîchissement.', 'publie'),
  ('decathlon-campus-gtb-villeneuve-d-ascq', 'Decathlon Campus — GTB', 'Bureaux et tertiaires', 'Villeneuve d''Ascq', 'Refonte du système de gestion technique du bâtiment (GTB).', 'publie'),
  ('smh-mutuelle-loos', 'SMH Mutuelle', 'Bureaux et tertiaires', 'Loos', 'Travaux de performance énergétique.', 'publie'),
  ('nacarat-courtepaille-marcq-en-barul', 'Nacarat — Courtepaille', 'Bureaux et tertiaires', 'Marcq-en-Barœul', 'Construction du siège La Flandre Assurance.', 'publie'),
  ('roland-garros-paris', 'Roland Garros', 'Equipements sportifs', 'Paris', 'Extension des tribunes Est et Ouest pour augmenter la jauge de 1000 personnes.', 'publie'),
  ('novalys-projets-residentiels', 'Novalys — Projets résidentiels', 'Logement', null, 'Études de conception d''opérations diverses.', 'publie')
on conflict (slug) do nothing;
